name: 🎒 UbiquiBag Order Request
description: Order a UbiquiBag using the DevPool Task OS
title: 🎒 UbiquiBag Order Request
labels: ["Priority: 4 (Urgent)", "Time: <5 Minutes"]
body:
  - type: markdown
    attributes:
      value: |
        ![black-bag-graphic-cropped](https://github.com/ubiquity/ubiquibar/assets/4975670/4868f1c7-b5bb-4733-9f49-a92a36f94c2a)
        ![white-bag-cropped-graphic](https://github.com/ubiquity/ubiquibar/assets/4975670/a5f137a9-5bb7-4d69-b6a0-9966979e1e80)

  - type: dropdown
    id: color
    attributes:
      label: What color would you like?
      options:
        - Black
        - White
    validations:
      required: true
  - type: textarea
    id: remarks
    attributes:
      label: Order remarks
      description: Do you have any extra remarks to add?
